controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
api_graphql_entrypoint:
    path: /api/graphql
    controller: api_platform.graphql.action.entrypoint